cms_artist:
    resource: "@CMSArtistBundle/Controller/"
    type:     annotation
    prefix:   /

cms_house:
    resource: "@CMSHouseBundle/Controller/"
    type:     annotation
    prefix:   /

cms_general_entries:
    resource: "@CMSGeneralEntriesBundle/Controller/"
    type:     annotation
    prefix:   /

cms_city:
    resource: "@CMSCityBundle/Controller/"
    type:     annotation
    prefix:   /

news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /

pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

cms_login:
    resource: "@UserBundle/Controller"
    prefix:   /
    type: annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /
